### ISSUE TITLE
class action

### ISSUE THREAD

**Issue by parsect** [alfiedotwtf/AABillFAQ#4]
People bought phones on the understanding personal data and messaging was secure and private. Now the government has intentionally weakened those phones is a class action to recover phone costs possible?

**Comment by cyphar** [comment]
The first question would be who would you sue? Class actions need to have a target, and you can't really sue a company for a change in legislation -- they aren't at fault.

You could argue that you should sue the Commonwealth, but (as is the case in most countries) you can only sue the Commonwealth for things that Parliament has specifically prescribed laws to allow you to sue them. This is outlined in s78 of the Australian Constitution:

> 78. The Parliament may make laws conferring rights to proceed against the Commonwealth or a State in respect of matters within the limits of the judicial power.

In addition, suits against the Commonwealth have to occur in High Court since it has original jurisdiction (as per s75(iii)). So there is no way to appeal such a decision.

**Comment by alfiedotwtf** [comment]
Thanks for the comments. Agree with Cyphar. Closing this issue.
